"""Book name/abbreviation aliases for parsing free-text passage references."""

# book_id -> list of accepted lowercase, space/period-free aliases
ALIASES = {
    "GEN": ["genesis", "gen", "ge"],
    "EXO": ["exodus", "exod", "exo", "ex"],
    "LEV": ["leviticus", "lev", "le"],
    "NUM": ["numbers", "num", "nu", "nm"],
    "DEU": ["deuteronomy", "deut", "deu", "dt"],
    "JOS": ["joshua", "josh", "jos"],
    "JDG": ["judges", "judg", "jdg", "jgs"],
    "RUT": ["ruth", "rut", "ru"],
    "1SA": ["1samuel", "1sam", "1sa"],
    "2SA": ["2samuel", "2sam", "2sa"],
    "1KI": ["1kings", "1kgs", "1ki"],
    "2KI": ["2kings", "2kgs", "2ki"],
    "1CH": ["1chronicles", "1chron", "1chr", "1ch"],
    "2CH": ["2chronicles", "2chron", "2chr", "2ch"],
    "EZR": ["ezra", "ezr"],
    "NEH": ["nehemiah", "neh"],
    "EST": ["esther", "esth", "est"],
    "JOB": ["job"],
    "PSA": ["psalms", "psalm", "psa", "ps", "pss"],
    "PRO": ["proverbs", "prov", "pro", "prv"],
    "ECC": ["ecclesiastes", "eccl", "eccles", "ecc"],
    "SNG": ["songofsolomon", "songofsongs", "song", "sos", "canticles"],
    "ISA": ["isaiah", "isa", "is"],
    "JER": ["jeremiah", "jer"],
    "LAM": ["lamentations", "lam"],
    "EZK": ["ezekiel", "ezek", "eze"],
    "DAN": ["daniel", "dan"],
    "HOS": ["hosea", "hos"],
    "JOL": ["joel", "jol"],
    "AMO": ["amos", "amo", "am"],
    "OBA": ["obadiah", "obad", "oba"],
    "JON": ["jonah", "jon", "jnh"],
    "MIC": ["micah", "mic"],
    "NAM": ["nahum", "nah", "nam"],
    "HAB": ["habakkuk", "hab"],
    "ZEP": ["zephaniah", "zeph", "zep"],
    "HAG": ["haggai", "hag"],
    "ZEC": ["zechariah", "zech", "zec"],
    "MAL": ["malachi", "mal"],
    "MAT": ["matthew", "matt", "mat", "mt"],
    "MRK": ["mark", "mrk", "mk"],
    "LUK": ["luke", "luk", "lk"],
    "JHN": ["john", "jhn", "jn"],
    "ACT": ["acts", "act"],
    "ROM": ["romans", "rom", "ro"],
    "1CO": ["1corinthians", "1cor", "1co"],
    "2CO": ["2corinthians", "2cor", "2co"],
    "GAL": ["galatians", "gal"],
    "EPH": ["ephesians", "eph"],
    "PHP": ["philippians", "phil", "php"],
    "COL": ["colossians", "col"],
    "1TH": ["1thessalonians", "1thess", "1th"],
    "2TH": ["2thessalonians", "2thess", "2th"],
    "1TI": ["1timothy", "1tim", "1ti"],
    "2TI": ["2timothy", "2tim", "2ti"],
    "TIT": ["titus", "tit"],
    "PHM": ["philemon", "phlm", "phm"],
    "HEB": ["hebrews", "heb"],
    "JAS": ["james", "jas", "jm"],
    "1PE": ["1peter", "1pet", "1pe"],
    "2PE": ["2peter", "2pet", "2pe"],
    "1JN": ["1john", "1jn"],
    "2JN": ["2john", "2jn"],
    "3JN": ["3john", "3jn"],
    "JUD": ["jude", "jud"],
    "REV": ["revelation", "revelations", "rev"],
}

REVERSE_ALIASES = {alias: book_id for book_id, aliases in ALIASES.items() for alias in aliases}
